broker_url: "raspberrypi.local"
port: 1883

raw_topic: "pi/weather_data"

dashboard_port: 5000
buffer_size: 200
log_sqlite: true
terminal_output: true

sample_interval: 1
db_name: "weather_anomalies.db"
model_path: "model_training/models/isolation_forest.joblib"

# OPTIONAL
# username: "name"
# password: "password"