broker_url: "localhost"
port: 1883

raw_topic: "pi/weather_data"
anomaly_topic: "pi/weather_anomalies"

dashboard_port: 5000
buffer_size: 200
log_sqlite: true
terminal_output: true

sample_interval: 1

#OPTIONAL
username: "name"
password: "password"